/global/cscratch1/sd/abault/tomo_challenge/bin/../tomo_challenge/data.py:89: UserWarning: Setting inf (undetected) bands to mag=30
  warnings.warn("Setting inf (undetected) bands to mag=30")
/global/cscratch1/sd/abault/tomo_challenge/bin/../tomo_challenge/metrics.py:153: RuntimeWarning: invalid value encountered in double_scalars
  (bz*nz_bin).sum()/(nz_bin).sum() for nz_bin in n_of_z]
Traceback (most recent call last):
  File "/global/cscratch1/sd/abault/tomo_challenge/bin/challenge_comb.py", line 115, in <module>
    main()
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/global/cscratch1/sd/abault/tomo_challenge/bin/challenge_comb.py", line 70, in main
    config['metrics'], metrics_fn, newbins)
  File "/global/cscratch1/sd/abault/tomo_challenge/bin/challenge_comb.py", line 105, in run_one
    scores = metrics_fn(results, valid_z, metrics=metrics)
  File "/global/cscratch1/sd/abault/tomo_challenge/bin/../tomo_challenge/metrics.py", line 57, in compute_scores
    tomo_bin, z, what)
  File "/global/cscratch1/sd/abault/tomo_challenge/bin/../tomo_challenge/metrics.py", line 195, in compute_mean_covariance
    C_sig[ci, cj] = ccl.angular_cl(cosmo, Ti, Tj, ell)
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/pyccl/cls.py", line 98, in angular_cl
    check(status, cosmo=cosmo_in)
  File "/global/homes/a/abault/.conda/envs/tomo/lib/python3.7/site-packages/pyccl/pyutils.py", line 48, in check
    raise CCLError("Error %s: %s" % (error_types[status], msg))
pyccl.errors.CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error

